### ISSUE TITLE
Getting a panic from trying to create a payment_link

### ISSUE THREAD

**Issue by binoculars** [andrewbaxter/terraform-provider-stripe#1]
```
 stripe_payment_link.Stripe_BasicSubscriptionPaymentLink_3468223B: Creating...
                2024-09-04T15:46:25.842-0400 [TRACE] provider.terraform-provider-stripe_v0.0.20: Received downstream response: @caller=github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tf5serverlogging/downstream_request.go:37 @module=sdk.proto tf_req_id=7cfcc6f7-fee6-cccd-7b71-011c6b5a102e diagnostic_error_count=0 diagnostic_warning_count=0 tf_proto_version=5.3 tf_provider_addr=provider tf_req_duration_ms=0 tf_resource_type=stripe_payment_link tf_rpc=PlanResourceChange timestamp=2024-09-04T15:46:25.840-0400
infrastructure  2024-09-04T15:46:25.842-0400 [TRACE] provider.terraform-provider-stripe_v0.0.20: Served request: tf_provider_addr=provider tf_req_id=7cfcc6f7-fee6-cccd-7b71-011c6b5a102e @module=sdk.proto tf_proto_version=5.3 tf_resource_type=stripe_payment_link tf_rpc=PlanResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:796 timestamp=2024-09-04T15:46:25.840-0400
                2024-09-04T15:46:25.845-0400 [TRACE] provider.terraform-provider-stripe_v0.0.20: Received request: @module=sdk.proto tf_proto_version=5.3 tf_req_id=76b84d8b-7c21-532d-d4a1-833783f32260 tf_resource_type=stripe_payment_link tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:805 tf_provider_addr=provider timestamp=2024-09-04T15:46:25.842-0400
infrastructure  2024-09-04T15:46:25.845-0400 [TRACE] provider.terraform-provider-stripe_v0.0.20: Sending request downstream: @module=sdk.proto tf_proto_version=5.3 tf_provider_addr=provider @caller=github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tf5serverlogging/downstream_request.go:17 tf_req_id=76b84d8b-7c21-532d-d4a1-833783f32260 tf_resource_type=stripe_payment_link tf_rpc=ApplyResourceChange timestamp=2024-09-04T15:46:25.842-0400
                2024-09-04T15:46:25.848-0400 [TRACE] provider.terraform-provider-stripe_v0.0.20: Calling downstream: @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:836 tf_req_id=76b84d8b-7c21-532d-d4a1-833783f32260 tf_resource_type=stripe_payment_link tf_rpc=ApplyResourceChange @module=sdk.helper_schema tf_provider_addr=provider timestamp=2024-09-04T15:46:25.843-0400
                2024-09-04T15:46:25.847-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
infrastructure  2024-09-04T15:46:25.848-0400 [TRACE] provider.terraform-provider-stripe_v0.0.20: Served request: @caller=runtime/panic.go:884 @module=sdk.proto tf_proto_version=5.3 tf_provider_addr=provider tf_req_id=76b84d8b-7c21-532d-d4a1-833783f32260 tf_resource_type=stripe_payment_link tf_rpc=ApplyResourceChange timestamp=2024-09-04T15:46:25.843-0400
                2024-09-04T15:46:25.850-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: panic: not a string
                2024-09-04T15:46:25.850-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20
                2024-09-04T15:46:25.850-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: goroutine 76 [running]:
                2024-09-04T15:46:25.850-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: github.com/hashicorp/go-cty/cty.Value.AsString({{{0x101556460?, 0x140001983f9?}}, {0x101544ba0?, 0x1400070a750?}})
                2024-09-04T15:46:25.850-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:1173 +0x130
                2024-09-04T15:46:25.850-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: main.fmtPath({0x1400070a780?, 0x3, 0x10127d76e?})
infrastructure  2024-09-04T15:46:25.850-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/andrewbaxter/terraform-provider-stripe/generated/main.go:169 +0xd0
                2024-09-04T15:46:25.852-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: main.resources_payment_link.func1.1.9.1.1(0x140000b6b08, {0x140002ad400, 0x1, 0x1}, 0x140000b6ad8, 0x140000b6dd0)
                2024-09-04T15:46:25.852-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/andrewbaxter/terraform-provider-stripe/generated/resources_payment_link.go:362 +0x174
                2024-09-04T15:46:25.852-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: main.resources_payment_link.func1.1.9.1(0x140000b6b08, {0x140002ad400, 0x1, 0x1}, 0x140000b6ad8, 0x140000b6dd0)
                2024-09-04T15:46:25.852-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/andrewbaxter/terraform-provider-stripe/generated/resources_payment_link.go:383 +0xd0
                2024-09-04T15:46:25.852-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: main.resources_payment_link.func1.1.9({0x140002ad400, 0x1, 0x1}, {0x101431220?, 0x1400019cf30?}, 0x0?)
infrastructure  2024-09-04T15:46:25.852-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/andrewbaxter/terraform-provider-stripe/generated/resources_payment_link.go:422 +0xf8
                2024-09-04T15:46:25.856-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: main.resources_payment_link.func1.1(0x140ab99496a?, 0x140000b6dd0)
                2024-09-04T15:46:25.856-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/andrewbaxter/terraform-provider-stripe/generated/resources_payment_link.go:426 +0x6ac
                2024-09-04T15:46:25.856-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: main.resources_payment_link.func1({0x101555e08, 0x140000889c0}, 0x0?, {0x101493d60?, 0x1400007e820})
                2024-09-04T15:46:25.856-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/andrewbaxter/terraform-provider-stripe/generated/resources_payment_link.go:807 +0x68
infrastructure  2024-09-04T15:46:25.856-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x14000527500, {0x101555e40, 0x1400009b770}, 0xd?, {0x101493d60, 0x1400007e820})
                2024-09-04T15:46:25.859-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:707 +0xe8
                2024-09-04T15:46:25.859-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000527500, {0x101555e40, 0x1400009b770}, 0x140000ab040, 0x14000129200, {0x101493d60, 0x1400007e820})
                2024-09-04T15:46:25.859-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0x86c
                2024-09-04T15:46:25.859-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000560018, {0x101555e40?, 0x1400009b650?}, 0x140000dea00)
infrastructure  2024-09-04T15:46:25.859-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xb70
                2024-09-04T15:46:25.861-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140002eaf00, {0x101555e40?, 0x1400009b020?}, 0x1400063ee70)
                2024-09-04T15:46:25.861-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x3b8
                2024-09-04T15:46:25.861-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10151f720?, 0x140002eaf00}, {0x101555e40, 0x1400009b020}, 0x1400063ee00, 0x0)
                2024-09-04T15:46:25.861-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
infrastructure  2024-09-04T15:46:25.861-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: google.golang.org/grpc.(*Server).processUnaryRPC(0x140002e81e0, {0x101559840, 0x14000003860}, 0x140000a8fc0, 0x140004cde00, 0x101a3e520, 0x0)
                2024-09-04T15:46:25.864-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        google.golang.org/grpc@v1.50.1/server.go:1340 +0xb7c
                2024-09-04T15:46:25.864-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: google.golang.org/grpc.(*Server).handleStream(0x140002e81e0, {0x101559840, 0x14000003860}, 0x140000a8fc0, 0x0)
                2024-09-04T15:46:25.864-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        google.golang.org/grpc@v1.50.1/server.go:1713 +0x82c
                2024-09-04T15:46:25.864-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: google.golang.org/grpc.(*Server).serveStreams.func1.2()
                2024-09-04T15:46:25.864-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        google.golang.org/grpc@v1.50.1/server.go:965 +0x84
                2024-09-04T15:46:25.864-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20: created by google.golang.org/grpc.(*Server).serveStreams.func1
infrastructure  2024-09-04T15:46:25.864-0400 [DEBUG] provider.terraform-provider-stripe_v0.0.20:        google.golang.org/grpc@v1.50.1/server.go:963 +0x290
                2024-09-04T15:46:25.867-0400 [ERROR] provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/andrewbaxter/stripe/0.0.20/darwin_arm64/terraform-provider-stripe_v0.0.20 id=24147 error="exit status 2"
infrastructure  ╷
                │ Error: Plugin did not respond
                │ 
                │   with stripe_payment_link.Stripe_BasicSubscriptionPaymentLink_3468223B (Stripe/BasicSubscriptionPaymentLink),
                │   on cdk.tf.json line 3947, in resource.stripe_payment_link.Stripe_BasicSubscriptionPaymentLink_3468223B (Stripe/BasicSubscriptionPaymentLink):
                │ 3947:       }
                │ 
                │ The plugin encountered an error, and failed to respond to the
                │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
                │ more details.
                ╵
infrastructure  Stack trace from the terraform-provider-stripe_v0.0.20 plugin:

                panic: not a string

                goroutine 76 [running]:
                github.com/hashicorp/go-cty/cty.Value.AsString({{{0x101556460?, 0x140001983f9?}}, {0x101544ba0?, 0x1400070a750?}})
                        github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:1173 +0x130
                main.fmtPath({0x1400070a780?, 0x3, 0x10127d76e?})
                        github.com/andrewbaxter/terraform-provider-stripe/generated/main.go:169 +0xd0
                main.resources_payment_link.func1.1.9.1.1(0x140000b6b08, {0x140002ad400, 0x1, 0x1}, 0x140000b6ad8, 0x140000b6dd0)
                        github.com/andrewbaxter/terraform-provider-stripe/generated/resources_payment_link.go:362 +0x174
                main.resources_payment_link.func1.1.9.1(0x140000b6b08, {0x140002ad400, 0x1, 0x1}, 0x140000b6ad8, 0x140000b6dd0)
                        github.com/andrewbaxter/terraform-provider-stripe/generated/resources_payment_link.go:383 +0xd0
                main.resources_payment_link.func1.1.9({0x140002ad400, 0x1, 0x1}, {0x101431220?, 0x1400019cf30?}, 0x0?)
infrastructure  github.com/andrewbaxter/terraform-provider-stripe/generated/resources_payment_link.go:422 +0xf8
                main.resources_payment_link.func1.1(0x140ab99496a?, 0x140000b6dd0)
                        github.com/andrewbaxter/terraform-provider-stripe/generated/resources_payment_link.go:426 +0x6ac
                main.resources_payment_link.func1({0x101555e08, 0x140000889c0}, 0x0?, {0x101493d60?, 0x1400007e820})
                        github.com/andrewbaxter/terraform-provider-stripe/generated/resources_payment_link.go:807 +0x68
                github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x14000527500, {0x101555e40, 0x1400009b770}, 0xd?, {0x101493d60, 0x1400007e820})
                        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:707 +0xe8
                github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000527500, {0x101555e40, 0x1400009b770}, 0x140000ab040, 0x14000129200, {0x101493d60, 0x1400007e820})
                        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0x86c
infrastructure  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000560018, {0x101555e40?, 0x1400009b650?}, 0x140000dea00)
                        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xb70
                github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140002eaf00, {0x101555e40?, 0x1400009b020?}, 0x1400063ee70)
                        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x3b8
                github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10151f720?, 0x140002eaf00}, {0x101555e40, 0x1400009b020}, 0x1400063ee00, 0x0)
                        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
                google.golang.org/grpc.(*Server).processUnaryRPC(0x140002e81e0, {0x101559840, 0x14000003860}, 0x140000a8fc0, 0x140004cde00, 0x101a3e520, 0x0)
                        google.golang.org/grpc@v1.50.1/server.go:1340 +0xb7c
infrastructure  google.golang.org/grpc.(*Server).handleStream(0x140002e81e0, {0x101559840, 0x14000003860}, 0x140000a8fc0, 0x0)
                        google.golang.org/grpc@v1.50.1/server.go:1713 +0x82c
                google.golang.org/grpc.(*Server).serveStreams.func1.2()
                        google.golang.org/grpc@v1.50.1/server.go:965 +0x84
                created by google.golang.org/grpc.(*Server).serveStreams.func1
                        google.golang.org/grpc@v1.50.1/server.go:963 +0x290

                Error: The terraform-provider-stripe_v0.0.20 plugin crashed!

                This is always indicative of a bug within the plugin. It would be immensely
                helpful if you could report the crash with the plugin's maintainers so that it
                can be fixed. The output above should help diagnose the issue.

                2024-09-04T15:46:27.128-0400 [DEBUG] provider: plugin exited
```

**Comment by andrewbaxter** [comment]
Ah thanks for the report! I'll take a look

**Comment by andrewbaxter** [comment]
Sorry that took some time.  I think this is fixed in 0.0.23 - it seems it was trying to format the attribute path for an error message and I hadn't handled all of the complexity hashicorp's path library brings with it.

**Comment by binoculars** [comment]
Thanks--trying it out now, but getting an error:

```
infrastructure  ╷
                │ Error: Field is missing but required. (at /line_items/0/enabled)
                │ 
                │   with stripe_payment_link.Stripe_BasicSubscriptionPaymentLink_3468223B (Stripe/BasicSubscriptionPaymentLink),
                │   on cdk.tf.json line 3947, in resource.stripe_payment_link.Stripe_BasicSubscriptionPaymentLink_3468223B (Stripe/BasicSubscriptionPaymentLink):
                │ 3947:       }
```

```typescript
    const basicSubscriptionPrice = new price.Price(this, 'BasicSubscriptionPrice', {
      product: basicProduct.id,
      currency: 'usd',
      unitAmount: config.subscriptionPrice,
      billingScheme: 'per_unit',
      recurringInterval: 'month',
      recurringIntervalCount: 1,
      taxBehavior: 'exclusive',
    });

    new paymentLink.PaymentLink(this, 'BasicSubscriptionPaymentLink', {
      lineItems: [{
        price: basicSubscriptionPrice.id,
        quantity: 1,
      }],
    });
```

**Comment by andrewbaxter** [comment]
Oh great! It looks like it worked. It crashed last time formatting the path in that error.

As the error states I think you need `enabled: true,` in your line item there.

**Comment by binoculars** [comment]
enabled is not a valid field on line_item--not sure why it's asking for that

**Comment by andrewbaxter** [comment]
Ah, you're right! Hmm, I feel like that may be a generated field needed to adapt the api schema to the terraform schema, but it doesn't show up in the documentation either.  Looking into it...

**Comment by andrewbaxter** [comment]
Okay, so I think this was referring to the field `adjustable_quantity_enabled` - the name in the stripe api is just `enabled` but in terraform to nest the field it became `adjustable_quantity_enabled`.  I fixed it to use the tf name instead.

However, there's another couple issues I noticed more directly related to the error.

1. It checks to see if any fields from the nested object are present, and if so makes the required fields in that object actually required (i.e. if the flattened nested object wasn't present in any form then it wouldn't run the required field checks for the nested object).  However, I think tf default values are making the fields "present" and triggering the required field check.

2. It wasn't actually checking all of the fields for present, just the required ones.  This is an easy fix.

I'm not sure the best way to handle 1.  Probably not specify defaults and handle nil values? I'm not sure tf supports that though, it might just return zero values.  Still looking...

**Comment by andrewbaxter** [comment]
(Background) Okay actually I think 2 was wrong so I didn't do that exactly.  That check was to enable the nested-field required field check, not act as a sentinel.  So basically, if any required fields are present from the nested object, it'll check all required fields.

I pushed 0.0.24 which I hope improves things, but I haven't had a chance to test.

Somehow TF was returning `adjustable_quantity_enabled` which tripped up the "is the nested object present" check. I'm curious if you set it before and then deleted/reset it? Otherwise TF just filled it in on its own, I guess.

So re: 1, what I ended up doing was adding a "zero value" check where if the value in the TF state/new config is a zero value, it treats it as if it's not present for nested value checks.  I think this may be necessary in fact... for example `GetOk` from TF has the description that it returns a boolean saying `whether or not the key has been set to a non-zero value at some point`.  Basically there's no "missing" or "unset" value, it seems that after it's been set once, even if you delete it later, it'll at best go back to the zero value.

In this case even though `adjustable_quantity_enabled` was being returned by TF from your config, I _assume_ it's false, so that will be treated as not present and the validation should pass.

Thanks for bearing with me here.  Let me know if this doesn't fix it.  Unfortunately I'm not in a good place to test this at the moment.

**Comment by binoculars** [comment]
I tried with

```ts
      lineItems: [{
        price: basicSubscriptionPrice.id,
        quantity: 1,
        adjustableQuantityEnabled: false,
      }],
```

as well as

```ts
      lineItems: [{
        price: basicSubscriptionPrice.id,
        quantity: 1,
      }], 
```

Still getting the same error:

```
infrastructure  stripe_payment_link.Stripe_BasicSubscriptionPaymentLink_3468223B: Creating...
infrastructure  ╷
                │ Error: Field is missing but required. (at /line_items/0/enabled)
                │ 
                │   with stripe_payment_link.Stripe_BasicSubscriptionPaymentLink_3468223B (Stripe/BasicSubscriptionPaymentLink),
                │   on cdk.tf.json line 3948, in resource.stripe_payment_link.Stripe_BasicSubscriptionPaymentLink_3468223B (Stripe/BasicSubscriptionPaymentLink):
                │ 3948:       }
                │ 
                ╵


0 Stacks deploying     1 Stack done     0 Stacks waiting
Invoking Terraform CLI failed with exit code 1
```

I can make a module that e2e tests the provider if you think that will be useful.

**Comment by andrewbaxter** [comment]
Ugh, sorry.  Yeah, a test case would help a lot, if you can.

That said, in 0.0.24 I changed the code to be
```
path := path.IndexInt(i).IndexString("adjustable_quantity_enabled")
...
Summary:       fmt.Sprintf("Field is missing but required. (at %s)", fmtPath(path)),
```
so it should say `at /line_items/0/adjustable_quantity_enabled` now, but I see it still says `/line_items/0/enabled`.  Can you double check that you've updated to 0.0.24 too?
